"""Add completed field to Task

Revision ID: 0af31ea2b69c
Revises: 
Create Date: 2026-03-20 10:14:24.633885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af31ea2b69c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable (SQLite limitation - cannot add NOT NULL columns to existing tables)
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    
    # Update existing rows to set default value
    op.execute("UPDATE task SET completed = False")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###
